/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.BUS_CategoryProduct;
import DTO.DTO_CategoryProduct;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EV
 */
public class CategoryProductGUI extends javax.swing.JFrame {

    /**
     * Creates new form CategoryProductGUI
     */
    public CategoryProductGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            addRowToJTable();
        } catch (SQLException ex) {
            Logger.getLogger(CustomerGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        btn_luuloaisanpham.setEnabled(false);
    }

    public void addRowToJTable() throws SQLException {
        BUS_CategoryProduct bus_categoryproduct = new BUS_CategoryProduct();
        ArrayList<DTO_CategoryProduct> list = bus_categoryproduct.getList();
        DefaultTableModel model = (DefaultTableModel) TableLoaiHangHoa.getModel();
        Object rowData[] = new Object[3];

        for (int i = 0; i < list.size(); i++) {
            System.out.println(list.get(i).getName());
            rowData[0] = list.get(i).getId();
            rowData[1] = list.get(i).getName();
            rowData[2] = list.get(i).getStatus();
            model.addRow(rowData);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableLoaiHangHoa = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        input_tenloai = new javax.swing.JTextField();
        btn_themloaisanpham = new javax.swing.JButton();
        btn_sualoaisanpham = new javax.swing.JButton();
        btn_xoaloaisanpham = new javax.swing.JButton();
        btn_luuloaisanpham = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        input_timkiemtenloai = new javax.swing.JTextField();
        btn_timkiemloaisanpham = new javax.swing.JButton();
        btn_huytimkiemloaisanpham = new javax.swing.JButton();
        input_timkiemtinhtrang = new javax.swing.JComboBox<>();
        input_timkiemmaloai = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        clockGUI1 = new GUI.Components.ClockGUI();
        header1 = new GUI.Components.Header();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(141, 169, 196));
        setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        TableLoaiHangHoa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TableLoaiHangHoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã loại", "Tên"
            }
        ));
        TableLoaiHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableLoaiHangHoaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableLoaiHangHoa);

        jPanel2.setBackground(new java.awt.Color(208, 244, 222));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Thông tin");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 110, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Mã loại");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 42, 82, 22));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Tên");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 82, 22));
        jPanel2.add(input_tenloai, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 300, -1));

        btn_themloaisanpham.setBackground(new java.awt.Color(103, 148, 54));
        btn_themloaisanpham.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_themloaisanpham.setForeground(new java.awt.Color(255, 255, 255));
        btn_themloaisanpham.setText("Thêm");
        btn_themloaisanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themloaisanphamActionPerformed(evt);
            }
        });
        jPanel2.add(btn_themloaisanpham, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 144, 40));

        btn_sualoaisanpham.setBackground(new java.awt.Color(255, 202, 58));
        btn_sualoaisanpham.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_sualoaisanpham.setForeground(new java.awt.Color(255, 255, 255));
        btn_sualoaisanpham.setText("Sửa");
        btn_sualoaisanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sualoaisanphamActionPerformed(evt);
            }
        });
        jPanel2.add(btn_sualoaisanpham, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 144, 40));

        btn_xoaloaisanpham.setBackground(new java.awt.Color(217, 4, 41));
        btn_xoaloaisanpham.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_xoaloaisanpham.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoaloaisanpham.setText("Xóa");
        jPanel2.add(btn_xoaloaisanpham, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 144, 40));

        btn_luuloaisanpham.setBackground(new java.awt.Color(56, 111, 164));
        btn_luuloaisanpham.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_luuloaisanpham.setForeground(new java.awt.Color(255, 255, 255));
        btn_luuloaisanpham.setText("Lưu");
        jPanel2.add(btn_luuloaisanpham, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 144, 40));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 300, 30));

        jPanel3.setBackground(new java.awt.Color(241, 192, 232));
        jPanel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Tìm kiếm");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Mã loại");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Tên");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Tình trạng");

        btn_timkiemloaisanpham.setBackground(new java.awt.Color(103, 148, 54));
        btn_timkiemloaisanpham.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_timkiemloaisanpham.setForeground(new java.awt.Color(255, 255, 255));
        btn_timkiemloaisanpham.setText("Tìm kiếm");

        btn_huytimkiemloaisanpham.setBackground(new java.awt.Color(217, 4, 41));
        btn_huytimkiemloaisanpham.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_huytimkiemloaisanpham.setForeground(new java.awt.Color(255, 255, 255));
        btn_huytimkiemloaisanpham.setText("Hủy tìm kiếm");

        input_timkiemtinhtrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        input_timkiemtinhtrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_timkiemtinhtrangActionPerformed(evt);
            }
        });

        input_timkiemmaloai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(input_timkiemtenloai, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(input_timkiemtinhtrang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(input_timkiemmaloai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_timkiemloaisanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_huytimkiemloaisanpham, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(input_timkiemmaloai, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(input_timkiemtenloai, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_timkiemtinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_timkiemloaisanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_huytimkiemloaisanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel19.setText("LOẠI HÀNG HÓA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header1, javax.swing.GroupLayout.DEFAULT_SIZE, 1203, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237)
                        .addComponent(clockGUI1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clockGUI1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themloaisanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themloaisanphamActionPerformed
        // TODO add your handling code here:
//        input_maloai.setEditable(true);
//        input_maloai.setEnabled(true);
//
//        input_tinhtrang.setEditable(true);
//        input_tinhtrang.setEnabled(true);
//
//        input_maloai.setSelectedIndex(0);
//        input_tenloai.setText("");
//        input_tinhtrang.setSelectedIndex(0);
//        input_mota.setText("");

        btn_themloaisanpham.setEnabled(false);
        btn_sualoaisanpham.setEnabled(false);
        btn_xoaloaisanpham.setEnabled(false);
        btn_luuloaisanpham.setEnabled(true);
    }//GEN-LAST:event_btn_themloaisanphamActionPerformed

    private void input_timkiemtinhtrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_timkiemtinhtrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_timkiemtinhtrangActionPerformed

    private void btn_sualoaisanphamActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_sualoaisanphamActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btn_sualoaisanphamActionPerformed

    private void TableLoaiHangHoaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TableLoaiHangHoaMouseClicked
        // TODO add your handling code here:
        int i = TableLoaiHangHoa.getSelectedRow();
        System.out.println(i);
        
        
        
//        jTextField1.setText((String) TableLoaiHangHoa.getModel().getValueAt(i, 0));
//        input_tenloai.setText(TableLoaiHangHoa.getModel().getValueAt(i, 1).toString());
//        if (TableLoaiHangHoa.getModel().getValueAt(i, 1).toString() == true) {
//            jCheckBox1.setSelected(true);
//        } 

//        input_maloai.setEditable(true);
//        input_tinhtrang.setEditable(true);

//        btn_themloaisanpham.setEnabled(true);
//        btn_sualoaisanpham.setEnabled(true);
//        btn_xoaloaisanpham.setEnabled(true);

    }// GEN-LAST:event_TableLoaiHangHoaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoryProductGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoryProductGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoryProductGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoryProductGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoryProductGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableLoaiHangHoa;
    private javax.swing.JButton btn_huytimkiemloaisanpham;
    private javax.swing.JButton btn_luuloaisanpham;
    private javax.swing.JButton btn_sualoaisanpham;
    private javax.swing.JButton btn_themloaisanpham;
    private javax.swing.JButton btn_timkiemloaisanpham;
    private javax.swing.JButton btn_xoaloaisanpham;
    private GUI.Components.ClockGUI clockGUI1;
    private GUI.Components.Header header1;
    private javax.swing.JTextField input_tenloai;
    private javax.swing.JComboBox<String> input_timkiemmaloai;
    private javax.swing.JTextField input_timkiemtenloai;
    private javax.swing.JComboBox<String> input_timkiemtinhtrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
