/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.BUS_CategoryProduct;
import BUS.BUS_Discount;
import BUS.BUS_Product;
import DTO.DTO_CategoryProduct;
import DTO.DTO_Discount;
import DTO.DTO_Product;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EV
 */
public class DiscountCategoryGUI extends javax.swing.JFrame {

    /**
     * Creates new form DiscountCategory
     */
    public DiscountCategoryGUI() {
        initComponents(); this.setLocationRelativeTo(null);
        try {
            addRowToJTable();
        } catch (SQLException ex) {
            Logger.getLogger(CustomerGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void addRowToJTable() throws SQLException {
        BUS_Discount bus_discount = new BUS_Discount();
        ArrayList<DTO_Discount> list = bus_discount.getList();
        DefaultTableModel model = (DefaultTableModel) TableGiamGia.getModel();
        Object rowData[] = new Object[7];

        for (int i = 0; i < list.size(); i++) {
            System.out.println(list.get(i).getName());
            rowData[0] = list.get(i).getId();
            rowData[1] = list.get(i).getName();
            rowData[2] = list.get(i).getStartDate();
            rowData[3] = list.get(i).getEndDate();
            rowData[4] = list.get(i).getPercent();
            rowData[5] = list.get(i).getCreateAt();
            rowData[6] = list.get(i).isIsDeleted();
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableGiamGia = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        input_ID = new javax.swing.JTextField();
        input_giamgia = new javax.swing.JTextField();
        input_ngayketthucgiamgia = new com.toedter.calendar.JDateChooser();
        input_ngaybatdaugiamgia = new com.toedter.calendar.JDateChooser();
        input_giamgiataoluc = new com.toedter.calendar.JDateChooser();
        input_Ten = new javax.swing.JTextField();
        input_daxoa = new javax.swing.JComboBox<>();
        btn_suagiamgia = new javax.swing.JButton();
        btn_xoagiamgia = new javax.swing.JButton();
        btn_luugiamgia = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        input_isDeleted = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        input_timkiemID = new javax.swing.JTextField();
        btn_timkiemgiamgia = new javax.swing.JButton();
        btn_huytimkiemgiamgia = new javax.swing.JButton();
        input_timkiemtinhtrang = new javax.swing.JComboBox<>();
        input_timkiemten = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        clockGUI1 = new GUI.Components.ClockGUI();
        header1 = new GUI.Components.Header();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(141, 169, 196));

        TableGiamGia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TableGiamGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên", "Ngày bắt đầu", "Ngày kết thúc", "Giảm giá", "Tạo lúc", "Đã xóa"
            }
        ));
        TableGiamGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableGiamGiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableGiamGia);

        jPanel2.setBackground(new java.awt.Color(208, 244, 222));
        jPanel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Thông tin");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Tên");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Giảm giá");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Ngày bắt đầu");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Ngày kết thúc");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Tạo lúc");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Đã xóa");

        input_giamgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_giamgiaActionPerformed(evt);
            }
        });

        input_daxoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_suagiamgia.setBackground(new java.awt.Color(255, 202, 58));
        btn_suagiamgia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_suagiamgia.setForeground(new java.awt.Color(255, 255, 255));
        btn_suagiamgia.setText("Sửa");
        btn_suagiamgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suagiamgiaActionPerformed(evt);
            }
        });

        btn_xoagiamgia.setBackground(new java.awt.Color(217, 4, 41));
        btn_xoagiamgia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_xoagiamgia.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoagiamgia.setText("Xóa");
        btn_xoagiamgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoagiamgiaActionPerformed(evt);
            }
        });

        btn_luugiamgia.setBackground(new java.awt.Color(56, 111, 164));
        btn_luugiamgia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_luugiamgia.setForeground(new java.awt.Color(255, 255, 255));
        btn_luugiamgia.setText("Lưu");
        btn_luugiamgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luugiamgiaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Đã xóa");

        input_isDeleted.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "true", "false"}));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(input_Ten)
                                .addComponent(input_ID)
                                .addComponent(input_ngaybatdaugiamgia, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(input_ngayketthucgiamgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(input_giamgiataoluc, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(input_isDeleted, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(input_giamgia, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(input_daxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_suagiamgia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoagiamgia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_luugiamgia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(input_ID))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(input_Ten)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_ngaybatdaugiamgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_ngayketthucgiamgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(input_giamgia)
                                .addGap(5, 5, 5)
                                .addComponent(input_giamgiataoluc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(input_isDeleted))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_daxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(152, 152, 152))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btn_suagiamgia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_xoagiamgia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_luugiamgia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel3.setBackground(new java.awt.Color(241, 192, 232));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Tìm kiếm");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("ID");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Tên");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Đã xóa");

        btn_timkiemgiamgia.setBackground(new java.awt.Color(103, 148, 54));
        btn_timkiemgiamgia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_timkiemgiamgia.setForeground(new java.awt.Color(255, 255, 255));
        btn_timkiemgiamgia.setText("Tìm kiếm");
        btn_timkiemgiamgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemgiamgiaActionPerformed(evt);
            }
        });

        btn_huytimkiemgiamgia.setBackground(new java.awt.Color(217, 4, 41));
        btn_huytimkiemgiamgia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_huytimkiemgiamgia.setForeground(new java.awt.Color(255, 255, 255));
        btn_huytimkiemgiamgia.setText("Hủy tìm kiếm");
        btn_huytimkiemgiamgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huytimkiemgiamgiaActionPerformed(evt);
            }
        });

        input_timkiemtinhtrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "true", "false"}));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(input_timkiemID)
                    .addComponent(input_timkiemtinhtrang, 0, 200, Short.MAX_VALUE)
                    .addComponent(input_timkiemten))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_timkiemgiamgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_huytimkiemgiamgia, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(input_timkiemID, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(input_timkiemten))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(input_timkiemtinhtrang)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_timkiemgiamgia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_huytimkiemgiamgia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(224, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel19.setText("GIẢM GIÁ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(293, 293, 293)
                        .addComponent(clockGUI1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clockGUI1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_xoagiamgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoagiamgiaActionPerformed
        // TODO add your handling code here:
        BUS_Discount tmp = new BUS_Discount();
        int i = TableGiamGia.getSelectedRow();
        int id = (int) TableGiamGia.getModel().getValueAt(i, 0);
        try {
            tmp.delete(id);

        } catch (SQLException ex) {
            Logger.getLogger(AccountGUI.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_xoagiamgiaActionPerformed

    private void btn_luugiamgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luugiamgiaActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel model = (DefaultTableModel) TableGiamGia.getModel();
            model.setRowCount(0);
            addRowToJTable();
        } catch (SQLException ex) {
            Logger.getLogger(AccountGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_luugiamgiaActionPerformed

    private void btn_huytimkiemgiamgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huytimkiemgiamgiaActionPerformed
        // TODO add your handling code here:

        BUS_Discount tmp = new BUS_Discount();
        try {
            tmp.getList();
            DefaultTableModel modeld = (DefaultTableModel) TableGiamGia.getModel();
            modeld.setRowCount(0);
            addRowToJTable();
        } catch (Exception ex) {
            Logger.getLogger(ProductGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        input_timkiemID.setText("");
        input_timkiemten.setText("");
        input_timkiemtinhtrang.setSelectedIndex(0);
    }//GEN-LAST:event_btn_huytimkiemgiamgiaActionPerformed

    private void btn_timkiemgiamgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemgiamgiaActionPerformed
        // TODO add your handling code here:

//        DTO_Discount pro = new DTO_Discount();
        BUS_Discount tmp = new BUS_Discount();
        if (!input_timkiemID.getText().equals("")) {
            try {
                DefaultTableModel modeld = (DefaultTableModel) TableGiamGia.getModel();
                modeld.setRowCount(0);
                ArrayList<DTO_Discount> list = tmp.getList();
                int searchNumb = Integer.parseInt(input_timkiemID.getText());
                DefaultTableModel model = (DefaultTableModel) TableGiamGia.getModel();
                Object rowData[] = new Object[12];
                tmp.getSingleById(searchNumb);
                for (int i = 0; i < list.size(); i++) {
                    if (list.get(i).getId() == searchNumb) {
                        rowData[0] = list.get(i).getId();
                        rowData[1] = list.get(i).getName();
                        rowData[2] = list.get(i).getStartDate();
                        rowData[3] = list.get(i).getEndDate();
                        rowData[4] = list.get(i).getPercent();
                        rowData[5] = list.get(i).getCreateAt();
                        rowData[6] = list.get(i).isIsDeleted();
                        model.addRow(rowData);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(ProductGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {

        }

        if (!input_timkiemten.getText().equals("")) {
            try {
                DefaultTableModel modeld = (DefaultTableModel) TableGiamGia.getModel();
                modeld.setRowCount(0);
                ArrayList<DTO_Discount> list = tmp.getList();
                String search = input_timkiemten.getText();
                DefaultTableModel model = (DefaultTableModel) TableGiamGia.getModel();
                Object rowData[] = new Object[12];
                for (int i = 0; i < list.size(); i++) {
                    if (list.get(i).getName().contains(search)) {
                        rowData[0] = list.get(i).getId();
                        rowData[1] = list.get(i).getName();
                        rowData[2] = list.get(i).getStartDate();
                        rowData[3] = list.get(i).getEndDate();
                        rowData[4] = list.get(i).getPercent();
                        rowData[5] = list.get(i).getCreateAt();
                        rowData[6] = list.get(i).isIsDeleted();
                        model.addRow(rowData);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(ProductGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
        }

        if (!input_timkiemtinhtrang.getSelectedItem().equals("--Select--")) {
            try {
                DefaultTableModel modeld = (DefaultTableModel) TableGiamGia.getModel();
                modeld.setRowCount(0);

                ArrayList<DTO_Discount> list = tmp.getList();
                Boolean searchStatus = Boolean.parseBoolean(input_timkiemtinhtrang.getSelectedItem().toString());
                DefaultTableModel model = (DefaultTableModel) TableGiamGia.getModel();

                Object rowData[] = new Object[12];
                for (int i = 0; i < list.size(); i++) {
//                 System.out.println(list.get(i).isStatus());
                    if (list.get(i).isIsDeleted() == searchStatus) {
                        rowData[0] = list.get(i).getId();
                        rowData[1] = list.get(i).getName();
                        rowData[2] = list.get(i).getStartDate();
                        rowData[3] = list.get(i).getEndDate();
                        rowData[4] = list.get(i).getPercent();
                        rowData[5] = list.get(i).getCreateAt();
                        rowData[6] = list.get(i).isIsDeleted();

                        model.addRow(rowData);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(ProductGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
        }
    }//GEN-LAST:event_btn_timkiemgiamgiaActionPerformed

    private void btn_suagiamgiaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_suagiamgiaActionPerformed
        // TODO add your handling code here:

//        DTO_Discount dis = new DTO_Discount();
//        BUS_Discount tmp = new BUS_Discount();
//        int a = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn sửa chứ!!");
//
//        if (a == JOptionPane.YES_OPTION) {
//
//            dis.setId(Integer.parseInt(input_ID.getText()));
//
//            dis.setName(input_Ten.getText());
//
//            String temp = new SimpleDateFormat("yyyy-MM-dd").format(input_ngaybatdaugiamgia.getDate());
//            dis.setStartDate(temp);
//
//            String temp1 = new SimpleDateFormat("yyyy-MM-dd").format(input_ngayketthucgiamgia.getDate());
//            dis.setEndDate(temp1);
//
//            String temp2 = new SimpleDateFormat("yyyy-MM-dd").format(input_giamgiataoluc.getDate());
//            dis.setCreateAt(temp2);
//
//            dis.setPercent(Float.parseFloat(input_giamgia.getText()));
//            dis.setIsDeleted(Boolean.parseBoolean(input_isDeleted.getSelectedItem().toString()));
//
//            try {
//                tmp.update(dis);
//            } catch (Exception ex) {
//                Logger.getLogger(ProductGUI.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
    }// GEN-LAST:event_btn_suagiamgiaActionPerformed

    private void input_giamgiaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_input_giamgiaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_input_giamgiaActionPerformed

    private void TableGiamGiaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TableGiamGiaMouseClicked
        // TODO add your handling code here:
        int i = TableGiamGia.getSelectedRow();
        System.out.println(i);
        input_ID.setText(TableGiamGia.getModel().getValueAt(i, 0).toString());
        input_Ten.setText(TableGiamGia.getModel().getValueAt(i, 1).toString());
        Date date;
        try {
            System.out.println("birst date :" + TableGiamGia.getModel().getValueAt(i, 2).toString());
            date = new SimpleDateFormat("yyyy-MM-dd").parse(TableGiamGia.getModel().getValueAt(i, 2).toString());
            input_ngaybatdaugiamgia.setDate(date);

        } catch (ParseException ex) {
            Logger.getLogger(AccountGUI.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        try {
            System.out.println("birst date :" + TableGiamGia.getModel().getValueAt(i, 3).toString());
            date = new SimpleDateFormat("yyyy-MM-dd").parse(TableGiamGia.getModel().getValueAt(i, 3).toString());
            input_ngayketthucgiamgia.setDate(date);

        } catch (ParseException ex) {
            Logger.getLogger(AccountGUI.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        input_giamgia.setText(TableGiamGia.getModel().getValueAt(i, 4).toString());
        try {
            System.out.println("birst date :" + TableGiamGia.getModel().getValueAt(i, 5).toString());
            date = new SimpleDateFormat("yyyy-MM-dd").parse(TableGiamGia.getModel().getValueAt(i, 5).toString());
            input_giamgiataoluc.setDate(date);

        } catch (ParseException ex) {
            Logger.getLogger(AccountGUI.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        input_daxoa.setSelectedItem(TableGiamGia.getModel().getValueAt(i, 6));
    }// GEN-LAST:event_TableGiamGiaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiscountCategoryGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE,
                            null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiscountCategoryGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE,
                            null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiscountCategoryGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE,
                            null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiscountCategoryGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE,
                            null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiscountCategoryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableGiamGia;
    private javax.swing.JButton btn_huytimkiemgiamgia;
    private javax.swing.JButton btn_luugiamgia;
    private javax.swing.JButton btn_suagiamgia;
    private javax.swing.JButton btn_timkiemgiamgia;
    private javax.swing.JButton btn_xoagiamgia;
    private GUI.Components.ClockGUI clockGUI1;
    private GUI.Components.Header header1;
    private javax.swing.JTextField input_ID;
    private javax.swing.JTextField input_Ten;
    private javax.swing.JComboBox<String> input_daxoa;
    private javax.swing.JTextField input_giamgia;
    private com.toedter.calendar.JDateChooser input_giamgiataoluc;
    private javax.swing.JComboBox<String> input_isDeleted;
    private com.toedter.calendar.JDateChooser input_ngaybatdaugiamgia;
    private com.toedter.calendar.JDateChooser input_ngayketthucgiamgia;
    private javax.swing.JTextField input_timkiemID;
    private javax.swing.JTextField input_timkiemten;
    private javax.swing.JComboBox<String> input_timkiemtinhtrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
