/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.BUS_Account;
import BUS.BUS_ImportDetail;
import BUS.BUS_ImportProduct;
import BUS.BUS_Order;
import BUS.BUS_OrderDetail;
import BUS.BUS_Suppilier;
import DTO.DTO_ImportDetail;
import DTO.DTO_ImportProduct;
import DTO.DTO_Order;
import DTO.DTO_OrderDetail;
import DTO.DTO_Suppilier;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import GUI.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author ADMIN
 */
public class ImportGUI extends javax.swing.JFrame {

    private ArrayList<DTO_ImportProduct> list = new ArrayList<>();

    public ImportGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            BUS_ImportProduct bus = new BUS_ImportProduct();
            list = bus.getList();
            addRowToJTable(list);
        } catch (SQLException ex) {
            Logger.getLogger(ImportGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImportIDTxt.setEditable(false);
    }

    public void addRowToJTable(ArrayList<DTO_ImportProduct> list) throws SQLException {
        DefaultTableModel model = (DefaultTableModel) ThongTinTable.getModel();
        model.setRowCount(0);
        Object rowData[] = new Object[4];

        for (int i = 0; i < list.size(); i++) {
            System.out.println(list.get(i).getId());
            rowData[0] = list.get(i).getId();
            rowData[1] = list.get(i).getImportDate();
            rowData[2] = list.get(i).getSuppilierId();
            rowData[3] = list.get(i).getAccountId();
            model.addRow(rowData);
        }
    }

    public void renderOrderDetail(int id) throws SQLException {

        BUS_ImportDetail bus_detail = new BUS_ImportDetail();
        ArrayList<DTO_ImportDetail> get_all = bus_detail.getList();
        ArrayList<DTO_ImportDetail> list = new ArrayList<>();

        System.out.print(get_all);
        DefaultTableModel model = (DefaultTableModel) ChiTietTable.getModel();
        model.setRowCount(0);
        Object rowData[] = new Object[5];
        for (int i = 0; i < get_all.size(); i++) {
//            System.out.println(get_all.get(i));
            if (get_all.get(i).getImportId() == id) {
                list.add(get_all.get(i));
            }
        }
//                System.out.print(list);
        for (int i = 0; i < list.size(); i++) {
            System.out.println(list.get(i));
            rowData[0] = list.get(i).getId();
            rowData[1] = list.get(i).getImportId();
            rowData[2] = list.get(i).getProductId();
            rowData[3] = list.get(i).getQuanity();
            rowData[4] = list.get(i).getPrice();
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DonHangLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ThongTinTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        XoaBtn = new javax.swing.JButton();
        SuaBtn = new javax.swing.JButton();
        OrderIDLbl = new javax.swing.JLabel();
        AccIDLbl = new javax.swing.JLabel();
        CustomerIDLbl = new javax.swing.JLabel();
        ThongTinLbl = new javax.swing.JLabel();
        OrderDateLbl = new javax.swing.JLabel();
        ImportIDTxt = new javax.swing.JTextField();
        SupplierIDTxt = new javax.swing.JTextField();
        AccountIDTxt = new javax.swing.JTextField();
        OrderDateCal = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        TimKiemBtn = new javax.swing.JButton();
        HuyTimKiemBtn = new javax.swing.JButton();
        TimKiemLbl = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        MaNhapTxt = new javax.swing.JTextField();
        MaNCCTxt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        accTxt = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        NgayNhap = new com.toedter.calendar.JDateChooser();
        jButton18 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ChiTietTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        header1 = new GUI.Components.Header();
        clockGUI1 = new GUI.Components.ClockGUI();
        btnRefresh1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DonHangLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        DonHangLbl.setText("NHẬP HÀNG");

        ThongTinTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ThongTinTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Import_ID", "Date", "Supplier_ID", "Account_ID"
            }
        ));
        ThongTinTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThongTinTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ThongTinTable);

        jPanel3.setBackground(new java.awt.Color(255, 231, 224));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        XoaBtn.setBackground(new java.awt.Color(204, 174, 220));
        XoaBtn.setText("XÓA");
        XoaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaBtnActionPerformed(evt);
            }
        });

        SuaBtn.setBackground(new java.awt.Color(204, 174, 220));
        SuaBtn.setText("SỬA");
        SuaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaBtnActionPerformed(evt);
            }
        });

        OrderIDLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        OrderIDLbl.setText("Mã nhập");

        AccIDLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AccIDLbl.setText("Mã nhà cung cấp");

        CustomerIDLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CustomerIDLbl.setText("Mã tài khoản");

        ThongTinLbl.setBackground(new java.awt.Color(255, 255, 255));
        ThongTinLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ThongTinLbl.setForeground(new java.awt.Color(255, 51, 51));
        ThongTinLbl.setText("Thông tin");

        OrderDateLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        OrderDateLbl.setText("Ngày");

        ImportIDTxt.setEditable(false);

        AccountIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountIDTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(ThongTinLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(AccIDLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OrderIDLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(ImportIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OrderDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(SupplierIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CustomerIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(AccountIDTxt)
                    .addComponent(OrderDateCal, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addGap(17, 17, 17))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(XoaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(SuaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(ThongTinLbl)
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrderIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OrderDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ImportIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(OrderDateCal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplierIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccountIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SuaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(XoaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 231, 213));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        TimKiemBtn.setBackground(new java.awt.Color(204, 174, 220));
        TimKiemBtn.setText("Tìm kiếm");
        TimKiemBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TimKiemBtnMouseClicked(evt);
            }
        });

        HuyTimKiemBtn.setBackground(new java.awt.Color(204, 174, 220));
        HuyTimKiemBtn.setText("Hủy tìm kiếm");
        HuyTimKiemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyTimKiemBtnActionPerformed(evt);
            }
        });

        TimKiemLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TimKiemLbl.setForeground(new java.awt.Color(255, 0, 51));
        TimKiemLbl.setText("Tìm kiếm");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Mã nhập");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Mã nhà cung cấp");

        MaNhapTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaNhapTxtActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("Mã tài khoản");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("Ngày nhập");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(TimKiemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(HuyTimKiemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MaNhapTxt)
                                    .addComponent(MaNCCTxt)
                                    .addComponent(accTxt)
                                    .addComponent(NgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))))
                    .addComponent(TimKiemLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(TimKiemLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaNhapTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaNCCTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TimKiemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HuyTimKiemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(NgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton18.setBackground(new java.awt.Color(255, 193, 7));
        jButton18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/back.png"))); // NOI18N
        jButton18.setLabel("BACK");
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton18MouseClicked(evt);
            }
        });
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        ChiTietTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ImportID", "ProductID", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ChiTietTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("THÔNG TIN PHIẾU NHẬP");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("CHI TIẾT PHIẾU NHẬP");

        btnRefresh1.setBackground(new java.awt.Color(204, 204, 204));
        btnRefresh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/reset-32px.png"))); // NOI18N
        btnRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(clockGUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton18)))
                                .addGap(9, 9, 9))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnRefresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DonHangLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(491, 491, 491)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DonHangLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRefresh1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clockGUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void displayDate() throws ParseException {
        Calendar ca = new GregorianCalendar();
        String day = ca.get(Calendar.DAY_OF_MONTH) + "";
        String month = ca.get(Calendar.MONTH) + 1 + "";
        String year = ca.get(Calendar.YEAR) + "";

        if (day.length() == 1) {
            day = "0" + day;
        }
        if (month.length() == 1) {
            month = "0" + month;
        }

        String dd = year + "-" + month + "-" + day;

        Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dd);
        OrderDateCal.setDate(date);
    }
    private void ThongTinTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongTinTableMouseClicked
        // TODO add your handling code here:
        ImportIDTxt.setEditable(false);
        int i = ThongTinTable.getSelectedRow();
        System.out.println(i);
        ImportIDTxt.setText(ThongTinTable.getModel().getValueAt(i, 0).toString());
        SupplierIDTxt.setText(ThongTinTable.getModel().getValueAt(i, 2).toString());
//        jTextField17.setText(jTable1.getModel().getValueAt(i, 3).toString());
        Date date;
        try {
            date = new SimpleDateFormat("yyyy-MM-dd").parse(ThongTinTable.getModel().getValueAt(i, 1).toString());
            OrderDateCal.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(ImportGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        AccountIDTxt.setText(ThongTinTable.getModel().getValueAt(i, 3).toString());

        try {
            renderOrderDetail((int) ThongTinTable.getModel().getValueAt(i, 0));
        } catch (SQLException ex) {
            Logger.getLogger(ImportGUI.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_ThongTinTableMouseClicked

    private void SuaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaBtnActionPerformed
        // TODO add your handling code here:
        BUS_ImportProduct bus = new BUS_ImportProduct();
        DTO_ImportProduct dto = new DTO_ImportProduct();
        int a = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn sửa chứ?");
        if (a == JOptionPane.YES_OPTION) {
            dto.setSuppilierId(Integer.parseInt(SupplierIDTxt.getText()));
            dto.setAccountId(Integer.parseInt(AccountIDTxt.getText()));
            String temp = new SimpleDateFormat("yyyy-MM-dd").format(OrderDateCal.getDate());
            dto.setImportDate(temp);
            try {
                bus.update(dto);
            } catch (SQLException ex) {
                Logger.getLogger(AccountGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            DefaultTableModel model = (DefaultTableModel) ThongTinTable.getModel();
            model.setRowCount(0);
            try {
                addRowToJTable(list);
            } catch (SQLException ex) {
                Logger.getLogger(ImportGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SuaBtnActionPerformed

    private void XoaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaBtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa chứ?");
        if (a == JOptionPane.YES_OPTION) {
            BUS_ImportProduct bus = new BUS_ImportProduct();
            int i = ThongTinTable.getSelectedRow();
            int id = (int) ThongTinTable.getModel().getValueAt(i, 0);
            try {
                bus.delete(id);
            } catch (SQLException ex) {
                Logger.getLogger(ImportGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        DefaultTableModel model = (DefaultTableModel) ThongTinTable.getModel();
        model.setRowCount(0);
        try {
            addRowToJTable(list);
        } catch (SQLException ex) {
            Logger.getLogger(ImportGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_XoaBtnActionPerformed

    private void AccountIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountIDTxtActionPerformed

    private void jButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseClicked
        // TODO add your handling code here:

        this.dispose();
        try {
            new HomeGUI().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ImportGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton18MouseClicked

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void TimKiemBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimKiemBtnMouseClicked
        // TODO add your handling code here:
        ArrayList<DTO_ImportProduct> filter = new ArrayList<>();
        ArrayList<DTO_ImportProduct> filter_ImportID = new ArrayList<>();
        ArrayList<DTO_ImportProduct> filter_accID = new ArrayList<>();
        ArrayList<DTO_ImportProduct> filter_SupplierID = new ArrayList<>();
        ArrayList<DTO_ImportProduct> filter_date = new ArrayList<>();
        String importid = MaNhapTxt.getText();
        String supllierid = MaNCCTxt.getText();
        String accid = accTxt.getText();
        Date d = NgayNhap.getDate();
        String date = "";
        if (d != null) {
            date = new SimpleDateFormat("yyyy-MM-dd").format(d);
        
        }

        
        if (importid.length() != 0) {
            filter.clear();
            for (int i = 0; i < list.size(); i++) {
                if (list.get(i).getId() == Integer.parseInt(importid)) {
                    filter_ImportID.add(list.get(i));
                }
            }
            filter = filter_ImportID;
        }
        if (accid.length() != 0) {
            filter.clear();
            for (int i = 0; i < list.size(); i++) {
                if (list.get(i).getAccountId() == Integer.parseInt(accid)) {
                    filter_accID.add(list.get(i));
                }
            }
            filter = filter_accID;
        }
        if (supllierid.length() != 0) {
            filter.clear();
            for (int i = 0; i < list.size(); i++) {
                if (list.get(i).getSuppilierId() == Integer.parseInt(supllierid)) {
                    filter_SupplierID.add(list.get(i));
                }
            }
            filter = filter_SupplierID;
        }
        if (date.length() != 0) {
            filter.clear();
            for (int i = 0; i < list.size(); i++) {
                System.out.print(list.get(i).getImportDate());
                if (list.get(i).getImportDate().contains(date)) {
                    System.out.print(list.get(i));
                    filter_date.add(list.get(i));
                }
            }
            filter = filter_date;
            
        }
            System.out.println(filter);
            try {
                addRowToJTable(filter);
            } catch (SQLException ex) {
                Logger.getLogger(ImportGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_TimKiemBtnMouseClicked

    private void HuyTimKiemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyTimKiemBtnActionPerformed
        // TODO add your handling code here:
        MaNCCTxt.setText("");
        accTxt.setText("");
        MaNhapTxt.setText("");
        Date date = new Date();
        NgayNhap.setDate(date);
        BUS_ImportProduct oder = new BUS_ImportProduct();
        try {
            list = oder.getList();
            addRowToJTable(list);
        } catch (SQLException ex) {
            Logger.getLogger(ImportGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_HuyTimKiemBtnActionPerformed

    private void MaNhapTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaNhapTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaNhapTxtActionPerformed

    private void btnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh1ActionPerformed
        // TODO add your handling code here:
        ImportIDTxt.setText("");
        AccountIDTxt.setText("");
        SupplierIDTxt.setText("");
        MaNCCTxt.setText("");
        accTxt.setText("");
        MaNhapTxt.setText("");
        OrderDateCal.setDate(null);
        NgayNhap.setDate(null);
        DefaultTableModel model = (DefaultTableModel) ThongTinTable.getModel();
        model.setRowCount(0);
        DefaultTableModel model2 = (DefaultTableModel) ChiTietTable.getModel();
        model2.setRowCount(0);
            BUS_ImportProduct bus = new BUS_ImportProduct();
        try {
            list = bus.getList();
            addRowToJTable(list);
        } catch (SQLException ex) {
            Logger.getLogger(ImportGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRefresh1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImportGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccIDLbl;
    private javax.swing.JTextField AccountIDTxt;
    private javax.swing.JTable ChiTietTable;
    private javax.swing.JLabel CustomerIDLbl;
    private javax.swing.JLabel DonHangLbl;
    private javax.swing.JButton HuyTimKiemBtn;
    private javax.swing.JTextField ImportIDTxt;
    private javax.swing.JTextField MaNCCTxt;
    private javax.swing.JTextField MaNhapTxt;
    private com.toedter.calendar.JDateChooser NgayNhap;
    private com.toedter.calendar.JDateChooser OrderDateCal;
    private javax.swing.JLabel OrderDateLbl;
    private javax.swing.JLabel OrderIDLbl;
    private javax.swing.JButton SuaBtn;
    private javax.swing.JTextField SupplierIDTxt;
    private javax.swing.JLabel ThongTinLbl;
    private javax.swing.JTable ThongTinTable;
    private javax.swing.JButton TimKiemBtn;
    private javax.swing.JLabel TimKiemLbl;
    private javax.swing.JButton XoaBtn;
    private javax.swing.JTextField accTxt;
    private javax.swing.JButton btnRefresh1;
    private GUI.Components.ClockGUI clockGUI1;
    private GUI.Components.Header header1;
    private javax.swing.JButton jButton18;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
