    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.BUS_ImportDetail;
import BUS.BUS_ImportProduct;
import BUS.BUS_Order;
import DTO.DTO_CategoryProduct;
import DTO.DTO_ImportDetail;
import DTO.DTO_ImportProduct;
import DTO.DTO_Order;
import java.util.Date;
import GUI.*;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ADMIN
 */
public class PhieuNhap extends javax.swing.JFrame {

    /**
     * Creates new form CustomerGUI
     */
    public PhieuNhap() {
        initComponents();
        try {
            addRowToJTableThongTin();
            addRowToJTableThongTinChiTiet();
        } catch (SQLException ex) {
            Logger.getLogger(PhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void addRowToJTableThongTin() throws SQLException {
        BUS_ImportProduct bus_importproduct = new BUS_ImportProduct();
        ArrayList<DTO_ImportProduct> list = bus_importproduct.getList();
        System.out.println(list);
        DefaultTableModel model = (DefaultTableModel) ThongTinTable.getModel();
        Object rowData[] = new Object[5];
        
        for (int i = 0; i < list.size(); i++) {
            System.out.println(list.get(i).getId());
            rowData[0] = list.get(i).getId();
            rowData[1] = list.get(i).getSuppilierId();
            rowData[2] = list.get(i).getAccountId();
            rowData[3] = list.get(i).getImportDate();
            rowData[4] = list.get(i).isStatus();
            model.addRow(rowData);
        }
    }
    public void addRowToJTableThongTinChiTiet() throws SQLException {
        BUS_ImportDetail bus_importdetail = new BUS_ImportDetail();
        ArrayList<DTO_ImportDetail> list = bus_importdetail.getList();
        DefaultTableModel model = (DefaultTableModel) ChiTietTable.getModel();
        Object rowData[] = new Object[5];
        
        for (int i = 0; i < list.size(); i++) {
            System.out.println(list.get(i).getId());
            rowData[0] = list.get(i).getId();
            rowData[1] = list.get(i).getProductId();
            rowData[2] = list.get(i).getPrice();
            rowData[3] = list.get(i).getQuanity();
            rowData[4] = list.get(i).isStatus();
            model.addRow(rowData);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        ThongTinLbl = new javax.swing.JLabel();
        MaPNLbl = new javax.swing.JLabel();
        MaPNTxt = new javax.swing.JTextField();
        NgayNhapLbl = new javax.swing.JLabel();
        MaNCCLbl = new javax.swing.JLabel();
        MaKHLbl = new javax.swing.JLabel();
        StatusLbl = new javax.swing.JLabel();
        MaNCCTxt = new javax.swing.JTextField();
        MaKHTxt = new javax.swing.JTextField();
        StatusTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ThongTinTable = new javax.swing.JTable();
        ThemBtn = new javax.swing.JButton();
        XoaBtn = new javax.swing.JButton();
        SuaBtn = new javax.swing.JButton();
        TaoMoiBtn = new javax.swing.JButton();
        NgayNhapCal = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        MaPnLbl = new javax.swing.JLabel();
        MaSPLbl = new javax.swing.JLabel();
        SoLuongLbl = new javax.swing.JLabel();
        GiaBanLbl = new javax.swing.JLabel();
        MaPNDetail = new javax.swing.JTextField();
        MaSPDetail = new javax.swing.JTextField();
        SoLuongDetail = new javax.swing.JTextField();
        GiaBanDetail = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ChiTietTable = new javax.swing.JTable();
        ThemDetailBtn = new javax.swing.JButton();
        XoaDetailBtn = new javax.swing.JButton();
        SuaChiTietBtn = new javax.swing.JButton();
        TaomoiDetailBtn = new javax.swing.JButton();
        TimKiem = new javax.swing.JLabel();
        TimKiemTxt = new javax.swing.JTextField();
        TimKiemBtn = new javax.swing.JButton();
        TinhTrang = new javax.swing.JLabel();
        TinhTrangDetail = new javax.swing.JTextField();
        TinhTrang1 = new javax.swing.JLabel();
        MaNhapDetail = new javax.swing.JTextField();
        Title = new javax.swing.JLabel();
        clockGUI1 = new GUI.Components.ClockGUI();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 725));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ThongTinLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ThongTinLbl.setForeground(new java.awt.Color(255, 102, 102));
        ThongTinLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ThongTinLbl.setText("Thông tin");
        ThongTinLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ThongTinLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ThongTinLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MaPNLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MaPNLbl.setText("Mã phiếu nhập");

        NgayNhapLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NgayNhapLbl.setText("Ngày nhập");

        MaNCCLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MaNCCLbl.setText("Mã nhà cung cấp");

        MaKHLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MaKHLbl.setText("Mã khách hàng");

        StatusLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StatusLbl.setText("Tình trạng");

        ThongTinTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SupplierID", "AccountId", "ImportDate", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ThongTinTable);

        ThemBtn.setText("Thêm");
        ThemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemBtnActionPerformed(evt);
            }
        });

        XoaBtn.setText("Xóa");
        XoaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaBtnActionPerformed(evt);
            }
        });

        SuaBtn.setText("Sửa");
        SuaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaBtnActionPerformed(evt);
            }
        });

        TaoMoiBtn.setText("Tạo mới");
        TaoMoiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaoMoiBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(MaPNLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MaPNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(StatusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(StatusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(NgayNhapLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MaNCCLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(MaKHLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MaNCCTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MaKHTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NgayNhapCal, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(ThemBtn)
                                .addGap(27, 27, 27)
                                .addComponent(XoaBtn)
                                .addGap(29, 29, 29)
                                .addComponent(SuaBtn)
                                .addGap(27, 27, 27)
                                .addComponent(TaoMoiBtn)))
                        .addGap(0, 127, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaPNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaPNLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NgayNhapLbl)
                    .addComponent(NgayNhapCal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaNCCLbl)
                    .addComponent(MaNCCTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaKHLbl)
                    .addComponent(MaKHTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusLbl)
                    .addComponent(StatusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThemBtn)
                    .addComponent(XoaBtn)
                    .addComponent(SuaBtn)
                    .addComponent(TaoMoiBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setPreferredSize(new java.awt.Dimension(1200, 700));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 102));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Chi tiết phiếu nhập");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MaPnLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MaPnLbl.setText("Mã phiếu nhập");

        MaSPLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MaSPLbl.setText("Mã sản phẩm");

        SoLuongLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SoLuongLbl.setText("Số lượng");

        GiaBanLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GiaBanLbl.setText("Giá bán");

        ChiTietTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ProductID", "Price", "Quantity", "ImportID", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ChiTietTable);

        ThemDetailBtn.setText("Thêm");
        ThemDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemDetailBtnActionPerformed(evt);
            }
        });

        XoaDetailBtn.setText("Xóa");
        XoaDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaDetailBtnActionPerformed(evt);
            }
        });

        SuaChiTietBtn.setText("Sửa");
        SuaChiTietBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaChiTietBtnActionPerformed(evt);
            }
        });

        TaomoiDetailBtn.setText("Tạo mới");
        TaomoiDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaomoiDetailBtnActionPerformed(evt);
            }
        });

        TimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TimKiem.setText("Mã SP:");

        TimKiemBtn.setText("Tìm kiếm");
        TimKiemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemBtnActionPerformed(evt);
            }
        });

        TinhTrang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TinhTrang.setText("Tình trạng");

        TinhTrang1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TinhTrang1.setText("Mã nhập");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(GiaBanLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(GiaBanDetail))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(SoLuongLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SoLuongDetail))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(MaSPLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MaSPDetail))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(MaPnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MaPNDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 78, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TimKiemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TimKiemBtn)))
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(ThemDetailBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(XoaDetailBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SuaChiTietBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TaomoiDetailBtn))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(TinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TinhTrangDetail)))
                        .addGap(214, 214, 214))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(TinhTrang1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MaNhapDetail)
                        .addGap(214, 214, 214))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MaPnLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MaPNDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MaSPLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MaSPDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(TimKiemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SoLuongLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SoLuongDetail))
                    .addComponent(TimKiemBtn))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GiaBanLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GiaBanDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TinhTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TinhTrangDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TinhTrang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MaNhapDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 21, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThemDetailBtn)
                    .addComponent(XoaDetailBtn)
                    .addComponent(SuaChiTietBtn)
                    .addComponent(TaomoiDetailBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("PHIẾU NHẬP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(302, 302, 302)
                        .addComponent(clockGUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clockGUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void XoaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaBtnActionPerformed
        // TODO add your handling code here:
        BUS_ImportProduct ip= new BUS_ImportProduct();
        int i = ThongTinTable.getSelectedRow();
        int id = (int) ThongTinTable.getModel().getValueAt(i, 0);
        try {
            ip.delete(id);
        } catch (SQLException ex) {
            Logger.getLogger(PhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_XoaBtnActionPerformed

    private void XoaDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaDetailBtnActionPerformed
        // TODO add your handling code here:
        BUS_ImportDetail ip= new BUS_ImportDetail();
        int i = ChiTietTable.getSelectedRow();
        int id = (int) ChiTietTable.getModel().getValueAt(i, 0);
        try {
            ip.delete(id);
        } catch (SQLException ex) {
            Logger.getLogger(PhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_XoaDetailBtnActionPerformed

    public void displayDate() throws ParseException
        {
            Calendar ca = new GregorianCalendar();
            String day = ca.get(Calendar.DAY_OF_MONTH) + "";
            String month = ca.get(Calendar.MONTH) + 1 + "";
            String year = ca.get(Calendar.YEAR) + "";

            if (day.length() == 1) {
                day = "0" + day;
            }
            if (month.length() == 1) {
                month = "0" + month;
            }

            String dd = year + "-" + month + "-" + day;

            Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dd);
            NgayNhapCal.setDate(date);
        }
    private void TaoMoiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaoMoiBtnActionPerformed
        // TODO add your handling code here:
        try {
            MaPNTxt.setText("");
            MaNCCTxt.setText("");
            StatusTxt.setText("");
            MaKHTxt.setText("");
            displayDate();
        } catch (ParseException ex) {
            Logger.getLogger(PhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TaoMoiBtnActionPerformed

    private void TaomoiDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaomoiDetailBtnActionPerformed
        // TODO add your handling code here:
        try {
            MaPNDetail.setText("");
            MaNCCTxt.setText("");
            StatusTxt.setText("");
            MaKHTxt.setText("");
            displayDate();
        } catch (ParseException ex) {
            Logger.getLogger(PhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TaomoiDetailBtnActionPerformed

    private void SuaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaBtnActionPerformed
        // TODO add your handling code here:
        BUS_ImportProduct bus= new BUS_ImportProduct();
        DTO_ImportProduct dto= new DTO_ImportProduct();
        int a=JOptionPane.showConfirmDialog(    null,"Bạn có chắc muốn sửa chứ!!");  
        // new AlertMessageYN();
        if(a == JOptionPane.YES_OPTION){  
            //acc.setAccountName(tfAccountname.getText());
            dto.setAccountId(Integer.parseInt(MaKHTxt.getText()));      
            dto.setId(Integer.parseInt(MaPNTxt.getText()));
            dto.setSuppilierId(Integer.parseInt(MaNCCTxt.getText()));
            if ("true".equals(StatusTxt.getText())) dto.setStatus(true);
            else dto.setStatus(false);
            String temp = new SimpleDateFormat("yyyy-MM-dd").format(NgayNhapCal.getDate());
            dto.setImportDate(temp);       
            int i = ThongTinTable.getSelectedRow();
            int id = (int) ThongTinTable.getModel().getValueAt(i, 0);        
            dto.setId(id);
            try {
                bus.update(dto);
            } catch (SQLException ex) {
                Logger.getLogger(PhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SuaBtnActionPerformed

    private void SuaChiTietBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaChiTietBtnActionPerformed
        // TODO add your handling code here:
        BUS_ImportDetail bus= new BUS_ImportDetail();
        DTO_ImportDetail dto= new DTO_ImportDetail();
        int a=JOptionPane.showConfirmDialog(    null,"Bạn có chắc muốn sửa chứ!!");  
        // new AlertMessageYN();
        if(a == JOptionPane.YES_OPTION){  
            //acc.setAccountName(tfAccountname.getText());
            dto.setId(Integer.parseInt(MaPNDetail.getText()));      
            dto.setImportId(Integer.parseInt(MaNhapDetail.getText()));
            dto.setPrice(Integer.parseInt(GiaBanDetail.getText()));
            dto.setProductId(Integer.parseInt(MaSPDetail.getText()));
            dto.setQuanity(Integer.parseInt(SoLuongDetail.getText()));
            if ("true".equals(StatusTxt.getText())) dto.setStatus(true);
            else dto.setStatus(false);     
            int i = ChiTietTable.getSelectedRow();
            int id = (int) ChiTietTable.getModel().getValueAt(i, 0);        
            dto.setId(id);
            try {
                bus.update(dto);
            } catch (SQLException ex) {
                Logger.getLogger(PhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SuaChiTietBtnActionPerformed

    private void ThemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemBtnActionPerformed
        // TODO add your handling code here:
        BUS_ImportProduct bus= new BUS_ImportProduct();
        DTO_ImportProduct dto= new DTO_ImportProduct();
        if (MaPNTxt.getText().isEmpty())
            new AlertWarning("Nhập thiếu ID!").setVisible(true);
        else if (MaKHTxt.getText().isEmpty())
            new AlertWarning("Nhập thiếu ID tài khoản!").setVisible(true);
        else if (StatusTxt.getText().isEmpty())
            new AlertWarning("Nhập thiếu Status!").setVisible(true);
        else if (MaNCCTxt.getText().isEmpty())
            new AlertWarning("Nhập thiếu ID nhà cung cấp!").setVisible(true);
        else {
            dto.setId(Integer.parseInt(MaPNTxt.getText()));
            dto.setAccountId(Integer.parseInt(MaKHTxt.getText()));
            dto.setSuppilierId(Integer.parseInt(MaNCCTxt.getText()));
            String temp = new SimpleDateFormat("yyyy-MM-dd").format(NgayNhapCal.getDate());
            dto.setImportDate(temp);
            if ("true".equals(StatusTxt.getText())) dto.setStatus(true);
            else dto.setStatus(false);  
            try {    
                bus.add(dto);            } catch (SQLException ex) {
                Logger.getLogger(OrderGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ThemBtnActionPerformed

    private void ThemDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemDetailBtnActionPerformed
        // TODO add your handling code here:
        BUS_ImportDetail bus= new BUS_ImportDetail();
        DTO_ImportDetail dto= new DTO_ImportDetail();
        if (MaPNDetail.getText().isEmpty())
            new AlertWarning("Nhập thiếu ID!").setVisible(true);
        else if (MaSPDetail.getText().isEmpty())
            new AlertWarning("Nhập thiếu ID sản phẩm!").setVisible(true);
        else if (GiaBanDetail.getText().isEmpty())
            new AlertWarning("Nhập thiếu giá bán!").setVisible(true);
        else if (TinhTrangDetail.getText().isEmpty())
            new AlertWarning("Nhập thiếu Status!").setVisible(true);
        else if (MaNhapDetail.getText().isEmpty())
            new AlertWarning("Nhập thiếu ID nhập!").setVisible(true);
        else if (SoLuongDetail.getText().isEmpty())
            new AlertWarning("Nhập thiếu số lượng!").setVisible(true);
        else {
            dto.setId(Integer.parseInt(MaPNDetail.getText()));
            dto.setImportId(Integer.parseInt(MaNhapDetail.getText()));
            dto.setPrice(Integer.parseInt(GiaBanDetail.getText()));
            dto.setProductId(Integer.parseInt(MaSPDetail.getText()));
            dto.setQuanity(Integer.parseInt(SoLuongDetail.getText()));
            if ("true".equals(TinhTrangDetail.getText())) dto.setStatus(true);
            else dto.setStatus(false);  
            try {    
                bus.add(dto);            } catch (SQLException ex) {
                Logger.getLogger(OrderGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ThemDetailBtnActionPerformed

    private void TimKiemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemBtnActionPerformed
        // TODO add your handling code here:
        BUS_ImportDetail bus= new BUS_ImportDetail();
        DTO_ImportDetail dto= new DTO_ImportDetail();
        DefaultTableModel model = (DefaultTableModel) ChiTietTable.getModel();
        model.setRowCount(0);
        ArrayList<DTO_ImportDetail> list = null;
        try {
            list = bus.getList();
        } catch (SQLException ex) {
            Logger.getLogger(PhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
        int search = Integer.parseInt(TimKiemTxt.getText().toString());
        DefaultTableModel model2 = (DefaultTableModel) ChiTietTable.getModel();
        Object rowData[] = new Object[12];
        try {
            bus.getSingleById(search);
        } catch (SQLException ex) {
            Logger.getLogger(PhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < list.size(); i++) {
            if (list.get(i).getId() == search) {
                System.out.println(list.get(i).getId());
                rowData[0] = list.get(i).getId();
                rowData[1] = list.get(i).getProductId();
                rowData[2] = list.get(i).getPrice();
                rowData[3] = list.get(i).getQuanity();
                rowData[4] = list.get(i).getImportId();
                rowData[4] = list.get(i).isStatus();
                model2.addRow(rowData);
            }
        }
    }//GEN-LAST:event_TimKiemBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhieuNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ChiTietTable;
    private javax.swing.JTextField GiaBanDetail;
    private javax.swing.JLabel GiaBanLbl;
    private javax.swing.JLabel MaKHLbl;
    private javax.swing.JTextField MaKHTxt;
    private javax.swing.JLabel MaNCCLbl;
    private javax.swing.JTextField MaNCCTxt;
    private javax.swing.JTextField MaNhapDetail;
    private javax.swing.JTextField MaPNDetail;
    private javax.swing.JLabel MaPNLbl;
    private javax.swing.JTextField MaPNTxt;
    private javax.swing.JLabel MaPnLbl;
    private javax.swing.JTextField MaSPDetail;
    private javax.swing.JLabel MaSPLbl;
    private com.toedter.calendar.JDateChooser NgayNhapCal;
    private javax.swing.JLabel NgayNhapLbl;
    private javax.swing.JTextField SoLuongDetail;
    private javax.swing.JLabel SoLuongLbl;
    private javax.swing.JLabel StatusLbl;
    private javax.swing.JTextField StatusTxt;
    private javax.swing.JButton SuaBtn;
    private javax.swing.JButton SuaChiTietBtn;
    private javax.swing.JButton TaoMoiBtn;
    private javax.swing.JButton TaomoiDetailBtn;
    private javax.swing.JButton ThemBtn;
    private javax.swing.JButton ThemDetailBtn;
    private javax.swing.JLabel ThongTinLbl;
    private javax.swing.JTable ThongTinTable;
    private javax.swing.JLabel TimKiem;
    private javax.swing.JButton TimKiemBtn;
    private javax.swing.JTextField TimKiemTxt;
    private javax.swing.JLabel TinhTrang;
    private javax.swing.JLabel TinhTrang1;
    private javax.swing.JTextField TinhTrangDetail;
    private javax.swing.JLabel Title;
    private javax.swing.JButton XoaBtn;
    private javax.swing.JButton XoaDetailBtn;
    private GUI.Components.ClockGUI clockGUI1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
